# Generated by Django 5.1.1 on 2024-10-03 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='quiz_profile',
        ),
        migrations.RenameField(
            model_name='attemptedquestion',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='html',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='attemptedquestion',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='html',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='question',
            name='maximum_marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='modified',
        ),
        migrations.AddField(
            model_name='attemptedquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='Default Choice', max_length=200, verbose_name='Choice Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.DeleteModel(
            name='QuizProfile',
        ),
    ]
